* Ruminative meta-evolutionary Effects (extremely Hypothetical)

Extrapolating from [file:./metavolution][metaevolution].

In analogy to the ruminative Baldwin Effect, using an information proccesing system to create a world model and make decisions based on it etc.
There would be hypothetical ruminative meta-evolutionary processes.

Mutation operators would not only take epigenetic data into acount in a simple input-output algorithmic system;

There would be representations /about/ evolutionary paths or adaptive biases somewhere, that eventually would be inputs to mutation operators.

Where? On what time scales? No clue. Something something viruses, transposable elements?

It would be an information processing that would have ideas about what to do with a tree of life or something, and having the ideas die, i.e.
there would be critisim based on something. 

-------------------

This would map in my mind onto what is said about *natures disposition to beauty*.

Is this actually different from /third order (meta-evolutionary Baldwin Effect)/? Not sure.
